# Connect 4 Game Demonstration

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from platform import python_version

from gamelearner import *
from connectx import Connect4Game, Connect4BasicPlayer

python_version()

'3.6.10'

## Game dynamics

In [2]:
game = Connect4Game()
game

Connect4Game()

In [3]:
game.roles

[1, 2]

In [4]:
game.marks

['X', 'O']

In [5]:
game.state

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [6]:
game.make_move((1, 3))
game.make_move((2, 3))
game.make_move((1, 4))
game.make_move((2, 3))
game.make_move((1, 2))

In [7]:
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ O _ _ _
_ _ X X X _ _


In [8]:
game.get_rewards()

{2: 0.0}

In [9]:
game.check_if_game_over()
game.game_over

False

In [10]:
game.moves

[(1, 3), (2, 3), (1, 4), (2, 3), (1, 2)]

In [11]:
game.turn

2

In [12]:
game.available_moves()

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
try:
    game.make_move((1, 1))
except ValueError as err:
    print(err)

It is not player 1's turn.


In [14]:
game.make_move((2, 5))
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ O _ _ _
_ _ X X X O _


In [15]:
game._pos_last

(0, 5)

In [16]:
game._fill_levels

array([0, 0, 1, 3, 1, 1, 0], dtype=int8)

In [17]:
game.make_move((1, 1))
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ O _ _ _
_ X X X X O _


In [18]:
game.game_over

True

In [19]:
print(game.winner)

1


In [20]:
game.get_rewards()

{2: 0.0}

In [21]:
game.moves

[(1, 3), (2, 3), (1, 4), (2, 3), (1, 2), (2, 5), (1, 1)]

In [22]:
game._pos_last

(0, 1)

In [23]:
game.reverse_move()
game.moves

[(1, 3), (2, 3), (1, 4), (2, 3), (1, 2), (2, 5)]

In [24]:
game._pos_last

(0, 5)

In [25]:
game.reverse_move()
game.moves

[(1, 3), (2, 3), (1, 4), (2, 3), (1, 2)]

In [26]:
game._pos_last

(0, 2)

In [27]:
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ O _ _ _
_ _ X X X _ _


In [28]:
game.reverse_move()
game.moves

[(1, 3), (2, 3), (1, 4), (2, 3)]

In [29]:
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ O _ _ _
_ _ _ X X _ _


In [30]:
game.make_move((1, 5))
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ O _ _ _
_ _ _ X X X _


In [31]:
game.get_rewards()

{2: 0.0}

In [32]:
game.make_move((2, 6))
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ O _ _ _
_ _ _ X X X O


In [33]:
game.make_move((1, 2))
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ O _ _ _
_ _ X X X X O


In [34]:
game.game_over, game.winner

(True, 1)

In [35]:
game.get_rewards()

{2: 0.0}

In [36]:
try:
    game.make_move((2, 1))
except AssertionError as err:
    print(err)

Game is already over.


### Playing with Two Human Players

In [37]:
players = [HumanPlayer("Jill"), HumanPlayer("Jack")]
players

[HumanPlayer('Jill'), HumanPlayer('Jack')]

In [38]:
game = Connect4Game()
game

Connect4Game()

In [39]:
game.show_state()
players[0].make_move(game, role=1)

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
Jill's turn (column from left): 3


In [40]:
game.show_state()
players[1].make_move(game, role=2)

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ X _ _ _
Jack's turn (column from left): 4


In [41]:
game.show_state()

_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ X O _ _


### Playing against the basic algorithm

In [42]:
game = Connect4Game()
players = [HumanPlayer("Jill"), Connect4BasicPlayer("Computer")]
ctrl = GameController(game, players)
ctrl.play()

Game of Connect 4 with 2 players ['Jill', 'Computer']
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
Jill's turn (column from left): 3
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ X _ _ _
Computer's turn (column from left): 2
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ O X _ _ _
Jill's turn (column from left): 3
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ X _ _ _
_ _ O X _ _ _
Computer's turn (column from left): 2
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ O X _ _ _
_ _ O X _ _ _
Jill's turn (column from left): 3
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ X _ _ _
_ _ O X _ _ _
_ _ O X _ _ _
Computer's turn (column from left): 3
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ _ X _ _ _
_ _ O X _ _ _
_ _ O X _ _ _
Jill's turn (column from left): 2
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
_ _ X X _ _ _
_ _ O X _ _ _
_ _ O X _ _ _
Computer's turn (column 

### Simulate game against random player

In [43]:
game = Connect4Game()
players = [Connect4BasicPlayer("Computer"), RandomPlayer("Random")]
ctrl = GameController(game, players)
ctrl.play()

Game of Connect 4 with 2 players ['Computer', 'Random']
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
Computer's turn (column from left): 3
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ X _ _ _
Random's turn (column from left): 1
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ O _ X _ _ _
Computer's turn (column from left): 6
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ O _ X _ _ X
Random's turn (column from left): 2
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ O O X _ _ X
Computer's turn (column from left): 4
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ O O X X _ X
Random's turn (column from left): 1
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ O _ _ _ _ _
_ O O X X _ X
Computer's turn (column from left): 5
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ O _ _ _ _ _
_ O O X X X X
Game over!
C

In [44]:
# Play 10 games against random player
game = Connect4Game()
players = [Connect4BasicPlayer("Computer"), RandomPlayer("Random")]
ctrl = GameController(game, players)
for i in range(10):
    ctrl.reset()
    ctrl.play(show=False)
    print(game.show_state())
    winner = ctrl.players_by_role[game.winner]
    print(f"Winner: {winner.name}")

_ _ _ _ _ _ _
X _ O _ O _ _
X _ O O X _ _
O _ X X O X _
X X O O X O O
O O X O X X X
None
Winner: Computer
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ O _ _ _ _
_ _ O O _ _ _
_ X X X X _ _
None
Winner: Computer
_ _ _ _ _ _ _
_ _ _ _ _ _ _
O _ X _ _ _ O
O O X _ _ O X
X X O _ _ X X
X O X O O O X
None
Winner: Computer
_ X _ _ _ _ _
_ X _ _ _ _ _
_ O _ _ _ _ _
O X _ O _ _ O
X O O X X X X
O X O X O X O
None
Winner: Computer
_ _ _ _ _ _ O
_ _ _ O _ _ X
_ _ _ X O _ O
_ O O O O _ X
X O X O X _ X
X X O O X X X
None
Winner: Computer
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ X _ _ _
_ _ _ X _ _ _
_ _ _ X _ X _
O _ O X O O _
None
Winner: Computer
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ O _ _ _ _
_ _ O O X _ _
_ _ O X X _ X
_ _ O X O _ X
None
Winner: Computer
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ O _ _ _
O _ X X X X O
None
Winner: Computer
_ _ O _ _ _ _
_ _ O _ _ _ _
_ _ O _ _ _ _
X _ O _ _ _ _
X _ X _ X _ O
O X O X X X O
None
Winner: Computer
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ _ _ _ _ _
_ _ 